### ISSUE TITLE
@auTO instead of !auTO

### ISSUE THREAD

**Issue by rosshadden** [mtimkovich/auTO#15]
Hey I just used auTO in a netplay tourney (thanks Corona) and had some feedback. This first bit of feedback is a very minor nitpick but it should be a very easy change if you agree with it.

I think it would be better if you talked with him instead of having him listen for commands. `@auTO report 3-2`, etc. This has the advantage of autocompleting his name, is a little less confusing (for the lay-melee player. uh, the me-lay man? the me-lay man) and I think it's a slightly better workflow.

Very cool project! Thank you very much for making it. :heart:

**Comment by mtimkovich** [comment]
Ha I was thinking the same thing yesterday! This is somewhat tricky to implement, but i'll see if I can make it work.
