### ISSUE TITLE
allow aliases

### ISSUE THREAD

**Issue by rosshadden** [mtimkovich/auTO#16]
The display name constraint was definitely the biggest source of confusion in the bracket I just ran. Despite me trying to tell people in multiple places in very bold text that they had to use the same display name, I ended up having to yell at people and fix them myself. Allowing aliases would be a great feature.

This may be a bit difficult. I think it depends on how much (if any) state discord bots are able to store. I've never made a discord bot but have a lot of experience making IRC bots back when IRC was all we had. If discord bots are long-running processes and you can store state in memory it would be pretty straightforward to create a table storing aliases for people.

Proposed workflow:
```
# add alias for current user
!auTO alias "ur-mom-lol"

# add alias for given user
!auTO alias @someUser "nobody"
```

This would associate their discord accounts with different names on challonge.

**Comment by mtimkovich** [comment]
Really good idea! (People always manage to not put in their discord username.) Changing the display name in Challonge is a pain, so this would be much better.
