### ISSUE TITLE
If a non-admin/to reports the final match the reporter gets the finalization dm and not the admin/TO that started the tournament

### ISSUE THREAD

**Issue by PaulDepping** [mtimkovich/auTO#19]
Also, the bot posts this in the chat afterwards
in this case tylltoons is a normal player and KingSSB would be the admin/TO
![image](https://user-images.githubusercontent.com/56696636/78043660-e80fbc00-7373-11ea-83cb-2dadc7ac06e4.png)

**Comment by mtimkovich** [comment]
Thanks for catching this! Should message the tournament creator instead now. (or it will as soon as I restart the bot)
