### ISSUE TITLE
Creating private channels for players

### ISSUE THREAD

**Issue by CometovArt** [mtimkovich/auTO#22]
The bot receives a couple of players from the table: @ Player1 vs @ Player2. Immediately after that, he creates a private channel in the discord, where he adds @ Player1 and @ Player2. And he writes a text in this channel, for example: "A duel has been assigned to you. @ Player1 vs @ Player2. To send the results, use! Report 0-2"

**Comment by MatthewPopa** [comment]
This would be a tangential solution for #18. The main issue of cluttering one channel would be solved.

The biggest con I could see from this solution is confusion for players when there is a new channel after every match they play, but I believe players can get used to it after a bit. On the other hand, this does allow for even less clutter for the general user by making the player's match channels only visible to them. However, I don't know if the pro outweighs the con.

Overall, this is still a solution and it's hard to judge which is better without putting it into practice.

**Comment by CometovArt** [comment]
Such functionality is implemented by the bot of the service https://www.game.tv/ (from which I would like to switch to your bot)

We had a series of tournaments like that, and the reviews are pretty positive. People willingly communicate with each other in private channels, see only their private channels, the administrator can easily monitor all pairs, read their correspondence and answer questions.

This is a positive experience.

**Comment by MatthewPopa** [comment]
One major problem I just realized while testing the bot: if every single player doesn't have their Challonge name set the same as their Discord name, the private channel functionality does not work. In this case #18 would still be a separate issue..

**Comment by CometovArt** [comment]
Yes, this is a problem. But it is decided by strict administration. A mandatory point of the tournament rules is to have a nickname in the discord the same as in the game.

**Comment by mtimkovich** [comment]
@CometovArt: I have a beta version of this feature to try out. You'll need to grant the bot the "Manage Channels" permissions, which you can do from Server Settings > Role > auTO > Manage Channels.

Let me know what you think and if you run into any issues.

**Comment by CometovArt** [comment]
@mtimkovich Yesterday I held the first tournament with a new chip. Everything worked correctly: the bot created private channels, deleted after the start of a new circle. I entered the results of the matches myself on the site.

Today I asked the players to send the results on their own using the command "!auTO report 2-0"

The tournament has begun. The bot has created 3 text channels and 3 voice channels. In one channel, the player sent the result. The bot accepted it and posted it in the grid on the site. Then deleted all 3 text channels and 1 voice channel (the pair that indicated the result).

After the start of the second round (tournament according to the Swiss system), the bot itself entered some result into the grid and again deleted all text channels.

**Comment by mtimkovich** [comment]
I must not be handling swiss tournaments correctly. I'll get that fixed for you.
